import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
    return (
        <>
            <Head>
                <title>Vincent Albertsson</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/wizard.ico" />
            </Head>
            <main>
                <div className="text-center">
                    <h1 className="text-3xl mt-10">
                        <span className="underline text-2xl">
                            Vincent Albertsson
                        </span>{' '}
                        <span className="duration-300 hover:opacity-70">
                            🧙
                        </span>
                    </h1>
                    <p className="mt-8">
                        I'm Vincent, and I{' '}
                        <span className="line-through opacity-50">
                            work magic
                        </span>{' '}
                        write code.
                    </p>
                    <p className="mt-8">
                        My goal is to run a successful company and reach $10,000
                        a month by 2025. A lofty goal, but worth a shot.
                    </p>
                    <p className="mt-8">
                        There is still a ways to go, but I want to take it more
                        seriously and start a{' '}
                        <span className="italic">
                            12 projects in 12 months challenge
                        </span>
                        . Check out the{' '}
                        <Link
                            href="/blog"
                            className="underline cursor-pointer text-emerald-600 dark:text-emerald-200 hover:text-emerald-700 dark:hover:text-emerald-300"
                        >
                            blog
                        </Link>{' '}
                        for more info. I'll add small updates or new things I
                        learn there.
                    </p>
                    <p className="mt-8">
                        Check out the{' '}
                        <Link
                            href="/projects"
                            className="underline cursor-pointer text-emerald-600 dark:text-emerald-200 hover:text-emerald-700 dark:hover:text-emerald-300"
                        >
                            projects
                        </Link>{' '}
                        page for stuff that I've made, which will be updated as
                        I work toward the challenge.
                    </p>
                </div>
            </main>
        </>
    )
}
